name: SquidLimiter
version: 1.1
description: Limit the number of squids and stuff
author: VicWhiten_and_davr
website: www.github.com/davr/MobLimiter
main: com.bukkit.vicwhiten.moblimiter.MobLimiter
commands:
  moblimiter:
    description: Use a SquidLimiter command
    usage: |
           /<command> [subcommand] [type]
           Example: /<command> setmax 1000- sets the squid max to 1000
           Example: /<command> purge - removes all squids
